#!/usr/bin/env python3
import re
import sys

LINE = re.compile(
    r'^\s*(0[xX][0-9A-Fa-f]{1,8})\s*=\s*\{\s*policy\s*=\s*"([a-z_]+)"'
    r'(?:\s*,\s*name\s*=\s*"([^"]*)")?')
WIDE = re.compile(r'\bwide\s*=\s*true\b')
MACWIDE = re.compile(r'\bmacwide\s*=\s*"([a-z_]+)"')

POLICY = {
    "lock": "Policy::Lock",
    "stretch": "Policy::Stretch",
    "lock_text": "Policy::LockText",
    "hug_left": "Policy::HugLeft",
    "hug_right": "Policy::HugRight",
    "lock_width": "Policy::LockWidth",
    "hide": "Policy::Hide",
}


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src, dst = sys.argv[1], sys.argv[2]

    rows, seen, errors = [], set(), 0
    with open(src, encoding="utf-8") as fh:
        for number, line in enumerate(fh, 1):
            if not line.strip() or line.lstrip().startswith("#") or line.lstrip().startswith("["):
                continue
            m = LINE.match(line)
            if not m:
                print("%s:%d: not a policy entry: %s" % (src, number, line.rstrip()),
                      file=sys.stderr)
                errors += 1
                continue
            crc = int(m.group(1), 16)
            policy = POLICY.get(m.group(2))
            if policy is None:
                print("%s:%d: unknown policy %r" % (src, number, m.group(2)), file=sys.stderr)
                errors += 1
                continue
            if crc in seen:
                print("%s:%d: duplicate CRC %#010x" % (src, number, crc), file=sys.stderr)
                errors += 1
                continue
            seen.add(crc)
            body = line.split("#", 1)[0]
            wide = WIDE.search(body) is not None
            macwide = "Policy::Lock"
            mm = MACWIDE.search(body)
            if mm:
                macwide = POLICY.get(mm.group(1))
                if macwide is None or not wide:
                    print("%s:%d: macwide needs a known policy and wide = true: %s"
                          % (src, number, line.rstrip()), file=sys.stderr)
                    errors += 1
                    continue
            rows.append((crc, policy, (m.group(3) or "").replace('"', ''), wide, macwide))

    if errors:
        return 1

    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// Generated by tools/hud/gen_hud_policy.py from\n")
        fh.write("// %s -- do not edit; edit the TOML and rebuild.\n" % src.replace("\\", "/"))
        fh.write("// %d windows.\n" % len(rows))
        for crc, policy, name, wide, macwide in rows:
            fh.write('{0x%08XU, %s, "%s", %s, %s},\n'
                     % (crc, policy, name, "true" if wide else "false", macwide))
    print("hud policy: %d windows -> %s" % (len(rows), dst), file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
