import json
import sys

t360 = json.load(open(sys.argv[1]))
t3ds = json.load(open(sys.argv[2]))
dllmap = {v: int(k, 16) for k, v in json.load(open(sys.argv[3])).items()}
out = open(sys.argv[4], "w", encoding="utf-8")

GENERIC = ("nullsub_", "Stub_", "GLAPIStub_", "GLAPI_GetOne", "GetAPISize")
out.write("# the engine API tables the game-logic DLL calls through\n")
out.write("# Generated by tools/ida/api_tables_to_toml.py from the GLAPIxxx::InitAPI decompiles of both builds.\n")
out.write("# A slot is `byte offset = method | 360 engine function | 3DS function`; the byte offset is what the\n")
out.write("# DLL adds to gpAPIxxx (the table object + 4, past its vptr), so slot i sits at 4*(i-1).\n")
out.write("# '-' on the 3DS side: the table is platform-specific or its InitAPI was not decompilable; a 360 name\n")
out.write("# that differs from the 3DS one is a stub shared by several slots (nullsub_1, GLAPIStub_ReturnFalse ...).\n\n")
tot = 0
out.write("[summary]\n")
out.write("tables = %d\n" % len(t360))
out.write("slots = %d\n" % sum(len(v) for v in t360.values()))
out.write("dll_globals = \"gpAPI<Name> at 0x883CA1D4.. in source declaration order (3dObj, 3DS, Audio, Camera, Debug, Emitter, Util, String, Engine, Package, Environment, NavMesh, Resource, Windows, PS3, WII, XBOX360, GameObj, Graphics, HUD, Input, Light, Logic, Movie, Physic, SaveGame, Network, Online, BSpline, Zone, Curve, SoftBody, MoveRecognition, Animation, DataMining, Content, Cutscene); 3DS, PS3, WII and MoveRecognition are never filled on 360\"\n")
out.write("filled_by = \"GameLogic_0002 (0x880A7000, export ordinal 2) from the array GLLogicMgrImp::SetAPIPointers (0x820DFC68) builds and DLL_Load_and_BindExports (0x821B1F60) passes; array index order 0 3dObj,1 Audio,2 Camera,3 Debug,4 Emitter,5 Util,6 String,7 Engine,8 Package,9 Environment,10 NavMesh,11 Resource,12 Windows,13 XBOX360,14 GameObj,15 Graphics,16 HUD,17 Input,18 Light,19 Logic,20 Movie,21 Physic,22 SaveGame,23 MemoryAlloc fn,24 MemoryFree fn,25 Network,27 Online,28 BSpline,29 Zone,30 Curve,31 SoftBody,33 Animation,34 DataMining,35 Content,36 PS3,37 Cutscene\"\n")
out.write("engine_objects = \"vtbl_GLAPIxxx at 0x820681F0.. (6 slots: DeletingDtor, GetAPISize, GetVersion, InitAPI, GetName, GetAPIStruct); GLLogicMgrImp::GLLogicMgrImp (0x820DC600) constructs them, g_API_<Name> in Default.xex points at table+4\"\n")
out.write("struct_names = \"APIxxx is the real source name: the 3DS symbols spell GLBaseAPI_t<APIPhysic,&APIPhysicName>\"\n\n")
for api in sorted(t360, key=lambda a: -len(t360[a])):
    short = api[5:]
    a = {int(k): v for k, v in t360[api].items()}
    b = {int(k): v for k, v in t3ds.get(api, {}).items()}
    out.write("[tables.%s]\n" % short)
    out.write("global_360 = \"%s\"\n" % ("0x%08X gpAPI%s" % (dllmap[short], short) if short in dllmap else "-"))
    out.write("slots = %d\n" % max(a))
    for k in range(1, max(a) + 1):
        n360 = a.get(k, "-")
        n3 = b.get(k, "-")
        method = n3.split("::")[-1] if n3.startswith("GLAPI") else (n360.split("::")[-1] if n360.startswith("GLAPI") and "::" in n360 else "slot%d" % k)
        out.write('"%d" = "+%d %s | %s | %s"\n' % (k, 4 * (k - 1), method, n360, n3))
        tot += 1
    out.write("\n")
out.close()
print("wrote", sys.argv[4], tot, "slots")
