import collections
import csv
import re
import sys

src, out, title = sys.argv[1], sys.argv[2], sys.argv[3]
lo = int(sys.argv[4], 16) if len(sys.argv) > 4 else 0
hi = int(sys.argv[5], 16) if len(sys.argv) > 5 else 0xFFFFFFFF
SKIP = re.compile(r"^(sub_|nullsub_|GameLogic_\d+|loc_|j_|\?|__|_|Ke[A-Z]|Nt[A-Z]|Rtl[A-Z]|Xam[A-Z]|X[A-Z][a-z]|Ex[A-Z]|Mm[A-Z]|Ob[A-Z]|Io[A-Z]|Dbg|Hal[A-Z]|start$|Stub_)")
AUTO = re.compile(r"^(g|vt)_[A-Za-z0-9]+_[0-9A-F]{4}$")

fams = collections.OrderedDict()
globs = []
n = 0
for r in csv.DictReader(open(src, encoding="utf-8")):
    ea = int(r["ea"], 16)
    if not (lo <= ea < hi):
        continue
    name = r["name"]
    if r["kind"] == "func":
        if SKIP.match(name):
            continue
        m = re.match(r"(GLInstanciate|[A-Za-z0-9]+?)(::|_|(?<=GLInstanciate))", name)
        fam = m.group(1) if m else "misc"
        fams.setdefault(fam, []).append((ea, name))
        n += 1
    elif (name.startswith(("g_", "vtbl_", "gpAPI")) or "::" in name) and not AUTO.match(name):
        globs.append((ea, name))

with open(out, "w", encoding="utf-8") as fp:
    fp.write("# %s\n" % title)
    fp.write("# Generated by tools/ida/names_csv_to_toml.py from an export_names.py dump; functions grouped by family\n")
    fp.write("# (the text before the first :: or _), placeholders and kernel imports skipped.\n\n")
    fp.write("[summary]\nfunctions = %d\nfamilies = %d\nglobals = %d\n\n" % (n, len(fams), len(globs)))
    for fam in sorted(fams, key=lambda k: (-len(fams[k]), k)):
        fp.write("[functions.%s]\n" % re.sub(r"[^A-Za-z0-9]", "_", fam))
        for ea, name in sorted(fams[fam]):
            fp.write('"0x%08X" = "%s"\n' % (ea, name.replace("\\", "\\\\").replace('"', '\\"')))
        fp.write("\n")
    fp.write("[globals]\n")
    for ea, name in sorted(globs):
        fp.write('"0x%08X" = "%s"\n' % (ea, name))
print("wrote", out, n, "functions", len(fams), "families", len(globs), "globals")
