import os
import sys

LANGUAGES = ("en", "fr", "es", "it", "de")


def load(path):
    try:
        import tomllib
    except ImportError:
        return load_subset(path)
    with open(path, "rb") as f:
        return tomllib.load(f)


def load_subset(path):
    tables, current = {}, None
    for raw in open(path, encoding="utf-8"):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current = tables.setdefault(line[1:-1].strip(), {})
            continue
        key, _, value = line.partition("=")
        value = value.strip()
        if current is None or not value.startswith('"') or not value.endswith('"'):
            sys.exit(f"{path}: cannot read: {raw.rstrip()}")
        current[key.strip()] = value[1:-1].replace('\\"', '"').replace("\\\\", "\\")
    return tables


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    source, out_dir, basename = sys.argv[1:]
    tables = load(source)
    if "en" not in tables:
        sys.exit(f"{source}: no [en] block, which every other language falls back to")
    reference = tables["en"]

    os.makedirs(out_dir, exist_ok=True)
    written = []
    for language in LANGUAGES:
        if language not in tables:
            continue
        own = tables[language]
        for key in own:
            if key not in reference:
                sys.exit(f"{source}: [{language}] has {key}, which [en] does not")
        path = os.path.join(out_dir, f"{basename}.{language}.txt")
        with open(path, "w", encoding="utf-8", newline="\n") as out:
            out.write(f"# NAME<TAB>text, generated by tools/pkz/make_strings.py from {os.path.basename(source)} -- do not edit.\n")
            out.write(f"# [{language}]: {sum(1 for k in reference if k in own)} of {len(reference)} strings translated, the rest English.\n")
            for key, english in reference.items():
                out.write(f"{key}\t{own.get(key, english)}\n")
        written.append(f"{language} ({sum(1 for k in reference if k in own)}/{len(reference)})")
    print(f"{basename}: {', '.join(written)}")


if __name__ == "__main__":
    main()
