import re
import sys

FIELDS = (("NAME", "label"), ("DESC", "description"), ("LOCKED", "unachieved_description"))
SCORE = ("SCORE", "gamerscore")

SECRET = (("REEOT_ACH_SECRET_NAME", "Unknown"),
          ("REEOT_ACH_SECRET_DESC", "This one stays hidden until you earn it."))


def parse(text):
    entries = []
    for block in text.split("[[achievements]]")[1:]:
        entry = {}
        for key, value in re.findall(r"^\s*(\w+)\s*=\s*(.+?)\s*$", block, re.M):
            entry[key] = value[1:-1] if value.startswith('"') else value
        if "id" in entry:
            entries.append(entry)
    return entries


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    source, destination = sys.argv[1], sys.argv[2]
    entries = parse(open(source, encoding="utf-8").read())
    if not entries:
        sys.exit(f"no achievements found in {source}")

    lines = [
        "# NAME<TAB>text, generated by tools/pkz/make_ach_strings.py -- do not edit.",
        f"# {len(entries)} achievements from {source.replace(chr(92), '/')}",
    ]
    for entry in entries:
        for suffix, key in FIELDS:
            text = entry.get(key, "")
            if text:
                lines.append(f"REEOT_ACH_{entry['id']}_{suffix}\t{text}")
        score = entry.get(SCORE[1], "")
        if score:
            lines.append(f"REEOT_ACH_{entry['id']}_{SCORE[0]}\t{score} G")
    for name, text in SECRET:
        lines.append(f"{name}\t{text}")

    with open(destination, "w", encoding="utf-8", newline="\n") as out:
        out.write("\n".join(lines) + "\n")
    print(f"{destination}: {len(lines) - 2} strings for {len(entries)} achievements")


if __name__ == "__main__":
    main()
