function(reeot_embed_directory)
    cmake_parse_arguments(ARG "" "ROOT;HEADER;SOURCES_VAR" "SKIP_DIRS" ${ARGN})
    if(NOT ARG_ROOT OR NOT ARG_HEADER OR NOT ARG_SOURCES_VAR)
        message(FATAL_ERROR "reeot_embed_directory requires ROOT, HEADER, SOURCES_VAR")
    endif()

    file(GLOB_RECURSE assets RELATIVE "${ARG_ROOT}" CONFIGURE_DEPENDS "${ARG_ROOT}/*")
    list(SORT assets)

    cmake_path(GET ARG_HEADER PARENT_PATH header_dir)
    set(out_dir "${header_dir}/embed")
    set(sources "")
    set(EOT_EMBED_DECLS "")
    set(EOT_EMBED_ENTRIES "")

    foreach(rel IN LISTS assets)
        set(skipped OFF)
        foreach(dir IN LISTS ARG_SKIP_DIRS)
            if(rel MATCHES "^${dir}/")
                set(skipped ON)
            endif()
        endforeach()
        if(skipped)
            continue()
        endif()

        string(REGEX REPLACE "[^A-Za-z0-9]" "_" ident "${rel}")
        set(symbol "eot_embed_${ident}")
        set(source "${out_dir}/${ident}.cpp")
        set(input "${ARG_ROOT}/${rel}")
        file(SIZE "${input}" size)

        add_custom_command(
            OUTPUT "${source}"
            COMMAND ${CMAKE_COMMAND}
                    -DINPUT=${input} -DSYMBOL=${symbol} -DOUTPUT=${source}
                    -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/embed_one.cmake"
            DEPENDS "${input}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/embed_one.cmake"
            COMMENT "Embedding ${rel}"
            VERBATIM)

        list(APPEND sources "${source}")
        string(APPEND EOT_EMBED_DECLS "extern const uint8_t ${symbol}[];\n")
        string(APPEND EOT_EMBED_ENTRIES "    {\"${rel}\", ${symbol}, ${size}},\n")
    endforeach()

    configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/embedded.h.in" "${ARG_HEADER}" @ONLY)
    set(${ARG_SOURCES_VAR} ${sources} PARENT_SCOPE)
endfunction()

function(reeot_embed_generated)
    cmake_parse_arguments(ARG "" "INPUT;NAME;ACCESSOR;HEADER;SOURCES_VAR" "" ${ARGN})
    if(NOT ARG_INPUT OR NOT ARG_NAME OR NOT ARG_ACCESSOR OR NOT ARG_HEADER OR NOT ARG_SOURCES_VAR)
        message(FATAL_ERROR "reeot_embed_generated requires INPUT, NAME, ACCESSOR, HEADER, SOURCES_VAR")
    endif()

    string(REGEX REPLACE "[^A-Za-z0-9]" "_" ident "${ARG_NAME}")
    set(symbol "eot_embed_${ident}")
    cmake_path(GET ARG_HEADER PARENT_PATH header_dir)
    set(source "${header_dir}/embed/${ident}.cpp")

    add_custom_command(
        OUTPUT "${source}"
        COMMAND ${CMAKE_COMMAND}
                -DINPUT=${ARG_INPUT} -DSYMBOL=${symbol} -DOUTPUT=${source} -DWITH_SIZE=ON
                -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/embed_one.cmake"
        DEPENDS "${ARG_INPUT}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/embed_one.cmake"
        COMMENT "Embedding ${ARG_NAME}"
        VERBATIM)

    file(WRITE "${ARG_HEADER}.in"
"// Generated by cmake/embed.cmake - do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

#include \"embedded.h\"

extern const uint8_t ${symbol}[];
extern const size_t ${symbol}_size;

namespace eot {

// ${ARG_NAME}: produced by the build and compiled in with its size.
inline EmbeddedAsset ${ARG_ACCESSOR}() { return {\"${ARG_NAME}\", ${symbol}, ${symbol}_size}; }

} // namespace eot
")
    configure_file("${ARG_HEADER}.in" "${ARG_HEADER}" COPYONLY)
    set(${ARG_SOURCES_VAR} "${source}" PARENT_SCOPE)
endfunction()
