#!/usr/bin/env python3
import argparse
import csv
import os
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pso_common import (COLUMNS, DEFAULT_SHADER_CACHE, REPO_ROOT, canonicalize,  # noqa: E402
                        collect_inputs, identity, is_capture, load_shader_masks, read_rows,
                        row_line)
from pso_paks import (DEFAULT_PAKS, TECHNIQUES, ancestors, load_directory,  # noqa: E402
                      load_index, load_paks)

FORMAT = """\
# eot-pso-set v2: the pipelines the renderer builds ahead of the draws that
# use them. Generated by tools/pso/pso_derive.py from the paks and the
# captures; do not edit. Tab-separated records:
#   core   <id> <pipeline row (header columns): the state; shaders,
#          declaration, strides and polygon offset empty>
#   vcore  <core> <core>    the state's motion-vector form (eot_motion_vectors)
#   vkey   <v|p> <key> <hashes>   a shader cache key with several containers:
#          the game keeps the first one loaded, the renderer builds with it
#   decl   <id> <declaration elements, hex>
#   pkg    <id> <name> <parent ids> <level 0/1>
#   shadow <pkg> <depthBias> <slope>        a level's shadow-camera offset
#   cap    <pipeline row>   the merged captures the set was made from
#          (the generator reads them back; not compiled in)
#   row    <pkg> <vs> <ps> <decl> <strides> <core> <bias> <m> <source>
#          <frame> <tags> <spec> <msaa> <vkey> <pkey>
#          pkg: the packages whose load queues the row (|-joined), 0 = the boot;
#          bias 0 none, 1 the material's (m: offset m*1e-5, slope m*2),
#          2 the level's shadow cameras, 3 literal (m = "depthBias/slope");
#          source c captured (frame: first drawn; tags: the packages it was
#          drawn under; spec: the specialization bits it was drawn with; a
#          derived row's is the alpha-test bit or ff, either),
#          d derived from the pak (likeliest first); msaa: how draws used it
#          under eot_msaa (bit 0 single-sample, bit 1 multisampled, 0 not
#          known: both are built); vkey/pkey: the vkey records of its
#          shaders' cache keys (empty: one container), whose live variant
#          the renderer builds it with
"""

DEFAULT_OUT = REPO_ROOT / "config" / "pso" / "eot_pso.tsv"
DEFAULT_INC = REPO_ROOT / "src" / "gpu" / "pipeline" / "cache" / "eot_pso.inc"
INSTALL = Path(os.environ.get("EOT_INSTALL", "D:/EdgeOfTimeRecompiled"))
DEFAULT_CAPTURES = [REPO_ROOT / "pso", REPO_ROOT / "out" / "build" / "win-amd64-relwithdebinfo" / "pso",
                    INSTALL / "pso"]

DRAW_COLUMNS = {"vsHash", "psHash", "spec", "layoutKey", "declRaw", "strides", "frame", "session",
                "package", "depthBias", "slopeScaledDepthBias", "targetScale", "msaa"}
CORE_COLUMNS = [c for c in COLUMNS if c not in DRAW_COLUMNS]

BIAS_NONE, BIAS_MATERIAL, BIAS_SHADOW, BIAS_LITERAL = 0, 1, 2, 3
SPEC_ALPHA_TEST = 0x2
SPEC_EITHER = 0xFF
ALPHA_SURE = 0.95
MAX_HITS = 48
MSAA_MIN_SESSIONS = 2
FLAG_BIASED = 0x100

DECL_TYPE_SIZE = {36: 4, 37: 8, 57: 12, 38: 16, 6: 4, 10: 2, 2: 1, 25: 4, 26: 8, 24: 2, 31: 4, 32: 8,
                  30: 2, 33: 4, 34: 8, 7: 4, 16: 4, 17: 4}
SETS_FOR_MESH = {0: (0,), 1: (1,), 2: (0, 2), 3: (1, 3), 4: (0,)}


VARIANT_MODE = "chain"

GLOBAL_SHADOW = {(24, "2")}

BOOT_PACKAGES = ("Main", "Common", "Legal", "FrontScreen", "01A_SMA_PortalRoom_Pip")


def is_level(name):
    return name[:1].isdigit()


def packed_strides(decl):
    ends = defaultdict(int)
    for i in range(0, len(decl), 24):
        e = bytes.fromhex(decl[i:i + 24])
        stream, off = int.from_bytes(e[0:2], "big"), int.from_bytes(e[2:4], "big")
        if stream == 0xFF:
            break
        size = DECL_TYPE_SIZE.get(int.from_bytes(e[4:8], "big") & 0x3F, 0)
        ends[stream] = max(ends[stream], off + size)
    return {s: (v + 3) & ~3 for s, v in ends.items()}


def strides_text(stream0, decl):
    st = [0] * 16
    for s, v in packed_strides(decl).items():
        if s < 16:
            st[s] = v
    st[0] = stream0
    return "|".join(str(x) for x in st)


def short_strides(full):
    parts = full.split("|")
    while len(parts) > 1 and parts[-1] == "0":
        parts.pop()
    return "|".join(parts)


class Row:
    __slots__ = ("r", "packages", "frame", "hits", "owners", "core", "bias", "m", "msaa",
                 "msaa_files", "msaa_prev")

    def __init__(self, r):
        self.r = r
        self.packages = {int(p, 16) for p in (r.get("package") or "").split("|") if p}
        self.frame = int(r.get("frame") or 0)
        self.hits = []
        self.owners = set()
        self.msaa = int(r.get("msaa") or 0)
        self.msaa_files = set()
        self.msaa_prev = 0


def core_of(r):
    return tuple(r[c] for c in CORE_COLUMNS)


def read_set_captures(path):
    p = Path(path)
    if not p.exists():
        return []
    header, out = None, []
    for line in p.read_text(encoding="utf-8").splitlines():
        if line.startswith("header\t"):
            header = line.split("\t", 1)[1].split(",")
        elif line.startswith("cap\t") and header:
            out.append(dict(zip(header, next(csv.reader([line.split("\t", 1)[1]])))))
    return out


def load_captures(inputs, masks, previous=None, room_ids=None):
    files = [p for p in collect_inputs(inputs) if is_capture(p) or p.name.startswith("eot_pipelines")]
    rows = {}
    sources = [(str(f), read_rows(f)[1]) for f in files]
    room_sessions = {src for src, rs in sources if room_ids is None or any(
        int(t, 16) in room_ids for r in rs for t in (r.get("package") or "").split("|") if t)}
    if previous:
        sources.append(("set", read_set_captures(previous)))
    stale = set()
    for src, rs in sources:
        for r in rs:
            vs, ps = int(r["vsHash"], 16), int(r["psHash"], 16)
            if masks is not None and (vs not in masks or (ps and ps not in masks)):
                stale.add((vs, ps))
                continue
            canonicalize(r, masks)
            k = identity(r)
            row = rows.get(k)
            if row is None:
                row = rows[k] = Row(r)
            else:
                row.packages |= {int(p, 16) for p in (r.get("package") or "").split("|") if p}
                f2 = int(r.get("frame") or 0)
                if f2 and (not row.frame or f2 < row.frame):
                    row.frame = f2
                row.msaa |= int(r.get("msaa") or 0)
            if src == "set":
                m = re.match(r"msaa(\d+)$", r.get("session") or "")
                row.msaa_prev = max(row.msaa_prev, int(m.group(1)) if m else 0)
            elif int(r.get("msaa") or 0) and src in room_sessions:
                row.msaa_files.add(src)
    if stale:
        print(f"[derive] {len(stale)} shader pair(s) not in the shader cache: their rows are dropped",
              file=sys.stderr)
    return sorted(rows.values(), key=lambda x: (x.frame or 1 << 62, identity(x.r))), len(files)


def material_features(m):
    h = m.header
    f = {"env": m.kind == "env"}
    for b in range(32):
        f[f"mf{b}"] = bool(h["materialFlags"] >> b & 1)
    for i, bm in enumerate(m.stage_blend[:4]):
        f[f"st{i}blend{bm}"] = True
    for bm in (1, 2, 3):
        f[f"anyblend{bm}"] = bm in m.stage_blend
    groups = {u[2] for u in m.uses}
    for g in (4, 8, 18, -1, -2):
        f[f"rg{g}"] = g in groups
    flags = 0
    for u in m.uses:
        flags |= u[3]
    for b in range(5):
        f[f"df{b}"] = bool(flags >> b & 1)
    f["nouse"] = not m.uses
    for k in ("byte72", "byte73", "byte74", "byte75", "byte132", "byte133", "unk80", "unk116",
              "unk240", "unk134"):
        f[f"{k}={h[k]}"] = True
    for k in ("unk44", "unk48", "unk56", "unk60", "unk64", "unk68", "unk76", "unk84", "unk88",
              "unk92", "unk96", "unk124", "unk212", "unk216", "unk236"):
        f[f"{k}!=0"] = h[k] != 0
    return f


def slot_features(s):
    f = {f"t{s.technique}": True, f"set{s.set}": True, "nops": s.ps == 0}
    for b in range(32):
        f[f"gf{b}"] = bool(s.generic_flags >> b & 1)
        f[f"lf{b}"] = bool(s.lighting_flags >> b & 1)
    sf = 0
    for x in s.stage_flags:
        sf |= x
    for b in range(20):
        f[f"sf{b}"] = bool(sf >> b & 1)
    return f


class Tree:
    def __init__(self, min_leaf=8, max_depth=14, min_gain=1e-3):
        self.min_leaf, self.max_depth, self.min_gain = min_leaf, max_depth, min_gain

    def fit(self, samples):
        merged = defaultdict(float)
        for f, y, w in samples:
            merged[(f, y)] += w
        names = sorted({n for f, _ in merged for n in f})
        col = {n: i for i, n in enumerate(names)}
        labels = sorted({y for _, y in merged}, key=repr)
        lab = {y: i for i, y in enumerate(labels)}
        keys = list(merged)
        X = np.zeros((len(keys), len(names)), dtype=bool)
        y = np.zeros(len(keys), dtype=np.int64)
        w = np.zeros(len(keys))
        for i, (f, yy) in enumerate(keys):
            X[i, [col[n] for n in f]] = True
            y[i] = lab[yy]
            w[i] = merged[(f, yy)]
        self.names, self.labels = names, labels
        Y = np.zeros((len(keys), len(labels)))
        Y[np.arange(len(keys)), y] = w
        self.root = self._grow(X, Y, np.arange(len(keys)), 0)
        return self

    @staticmethod
    def _entropy_rows(C):
        n = C.sum(axis=-1, keepdims=True)
        p = np.divide(C, n, out=np.zeros_like(C), where=n > 0)
        with np.errstate(divide="ignore", invalid="ignore"):
            h = -np.where(p > 0, p * np.log2(p), 0.0).sum(axis=-1)
        return h, n[..., 0]

    def _grow(self, X, Y, idx, depth):
        counts_v = Y[idx].sum(axis=0)
        counts = {self.labels[i]: float(v) for i, v in enumerate(counts_v) if v > 0}
        node = {"counts": counts, "n": int(len(idx))}
        if depth >= self.max_depth or len(idx) < 2 * self.min_leaf or len(counts) <= 1:
            return node
        Xi, Yi = X[idx], Y[idx]
        yes_n = Xi.sum(axis=0)
        cy = Xi.T.astype(float) @ Yi
        cn = counts_v[None, :] - cy
        hy, wy = self._entropy_rows(cy)
        hn, wn = self._entropy_rows(cn)
        total = counts_v.sum()
        base, _ = self._entropy_rows(counts_v[None, :])
        gain = base[0] - (wy / total) * hy - (wn / total) * hn
        ok = (yes_n >= self.min_leaf) & (len(idx) - yes_n >= self.min_leaf)
        gain = np.where(ok, gain, -1.0)
        best = int(np.argmax(gain))
        if gain[best] < self.min_gain:
            return node
        node["split"] = self.names[best]
        mask = Xi[:, best]
        node["yes"] = self._grow(X, Y, idx[mask], depth + 1)
        node["no"] = self._grow(X, Y, idx[~mask], depth + 1)
        return node

    def leaf(self, features):
        node = self.root
        while "split" in node:
            node = node["yes"] if node["split"] in features else node["no"]
        return node


def feature_set(d):
    return frozenset(k for k, v in d.items() if v)


class Model:
    def __init__(self, index, keys, inc_threshold=0.05, core_share=0.04):
        self.index = index
        self.keys = keys
        self.row_keys = {}
        self.row_spec = {}
        self.inc_threshold = inc_threshold
        self.core_share = core_share
        self._mf = {}

    def mfeat(self, pak, mi):
        k = (pak, mi)
        if k not in self._mf:
            self._mf[k] = feature_set(material_features(self.index[pak][mi]))
        return self._mf[k]

    def features(self, pak, mi, si):
        m = self.index[pak][mi]
        return self.mfeat(pak, mi) | feature_set(slot_features(m.slots[si]))

    def fit(self, rows):
        self.keys.learn(rows)
        core_samples = []
        drawn = defaultdict(set)
        for row in rows:
            if not row.hits:
                continue
            w = 1.0 / len(row.hits)
            for pak, mi, si in row.hits:
                core_samples.append((self.features(pak, mi, si), (row.core, row.bias), w))
                drawn[(pak, mi)].add(si)
        self.cores = Tree(min_leaf=6).fit(core_samples)
        alpha_samples = []
        for row in rows:
            if not row.hits or row.r.get("spec", "0") in ("0", ""):
                continue
            alpha = bool(int(row.r["spec"], 16) & SPEC_ALPHA_TEST)
            pak, mi, si = row.hits[0]
            alpha_samples.append((self.features(pak, mi, si) | {f"core={hash(row.core) & 0xFFFFF}"},
                                  alpha, 1.0))
        self.alpha = Tree(min_leaf=6).fit(alpha_samples) if alpha_samples else None
        inc_samples = []
        for (pak, mi), sis in drawn.items():
            m = self.index[pak][mi]
            sets = {m.slots[si].set for si in sis}
            for si, s in enumerate(m.slots):
                if s.set in sets:
                    inc_samples.append((self.features(pak, mi, si), si in sis, 1.0))
        self.inclusion = Tree(min_leaf=10).fit(inc_samples)
        self.inc_n = len(inc_samples)
        return self

    def inclusion_p(self, f):
        c = self.inclusion.leaf(f)["counts"]
        n = sum(c.values())
        return c.get(True, 0) / n if n > 0 else 0.0

    def spec_for(self, f, core):
        if self.alpha is None:
            return SPEC_EITHER
        c = self.alpha.leaf(f | {f"core={hash(core) & 0xFFFFF}"})["counts"]
        n = sum(c.values())
        p = c.get(True, 0) / n if n else 0.5
        return SPEC_ALPHA_TEST if p >= ALPHA_SURE else 0 if p <= 1 - ALPHA_SURE else SPEC_EITHER

    def included(self, f):
        return self.inclusion_p(f) >= self.inc_threshold

    def cores_for(self, f):
        c = self.cores.leaf(f)["counts"]
        n = sum(c.values())
        return [(k, v / n) for k, v in c.items() if v / n >= self.core_share]

    def derive(self, pak):
        out = {}
        owner_sets = defaultdict(set)
        for m in self.index[pak]:
            for vset, _, _, _ in m.uses:
                owner_sets[(m.kind, m.owner)].update(SETS_FOR_MESH.get(vset, (0,)))
        for mi, m in enumerate(self.index[pak]):
            uses = defaultdict(set)
            have = {s.set for s in m.slots}
            for vset, stride, _, _ in m.uses:
                for s in SETS_FOR_MESH.get(vset, (0,)):
                    uses[s].add(stride)
            if not uses:
                for s in (owner_sets[(m.kind, m.owner)] & have) or (have - {4}):
                    uses[s].add(0)
            bias_m = m.header["unk212"] if m.header["materialFlags"] & FLAG_BIASED else 0.0
            for si, s in enumerate(m.slots):
                if s.set not in uses:
                    continue
                pairs = [(v, q) for v in self.keys.variants(pak, "vs", s.vs_key, s.vs)
                         for q in self.keys.variants(pak, "ps", s.ps_key, s.ps)]
                f = self.features(pak, mi, si)
                p_inc = self.inclusion_p(f)
                if p_inc < self.inc_threshold:
                    continue
                for (core, bias), share in self.cores_for(f):
                    if bias == BIAS_LITERAL:
                        bias = BIAS_MATERIAL
                    if bias == BIAS_MATERIAL and not bias_m:
                        continue
                    mm = bias_m if bias == BIAS_MATERIAL else 0.0
                    for stride in uses[s.set]:
                        st = stride or packed_strides(s.decl).get(0, 0)
                        if not st:
                            continue
                        for vs, ps in pairs:
                            k = (vs, ps, s.decl, st, core, bias, round(mm, 6))
                            out[k] = max(out.get(k, 0.0), p_inc * share)
                            self.row_keys.setdefault((pak, k), (s.vs_key, s.ps_key))
                            sp = self.spec_for(f, core)
                            was = self.row_spec.get((pak, k), sp)
                            self.row_spec[(pak, k)] = sp if was == sp else SPEC_EITHER
        return out


class ShaderKeys:
    def __init__(self, index, directory):
        self.hash_keys = defaultdict(set)
        self.key_hashes = defaultdict(set)
        self.first = defaultdict(dict)
        self.drawn = defaultdict(Counter)
        self.mode = VARIANT_MODE
        for pak, mats in index.items():
            first = self.first[pak]
            for m in mats:
                for sl in m.slots:
                    self.hash_keys[("vs", sl.vs)].add(sl.vs_key)
                    self.key_hashes[("vs", sl.vs_key)].add(sl.vs)
                    first.setdefault(("vs", sl.vs_key), sl.vs)
                    if sl.ps_key:
                        self.hash_keys[("ps", sl.ps)].add(sl.ps_key)
                        self.key_hashes[("ps", sl.ps_key)].add(sl.ps)
                        first.setdefault(("ps", sl.ps_key), sl.ps)
        names = {pid: v[0] for pid, v in directory.items()}
        ids = {v[0]: pid for pid, v in directory.items()}
        depth = {}

        def d(pid, seen=()):
            if pid not in depth:
                parents = [q for q in directory.get(pid, ("", []))[1] if q not in seen]
                depth[pid] = 1 + max((d(q, seen + (pid,)) for q in parents), default=-1)
            return depth[pid]
        self.order = {}
        self.previous = {}
        for pak in index:
            pid = ids.get(pak)
            chain = ancestors(directory, pid) if pid is not None else []
            chain = sorted((q for q in chain if q != pid), key=lambda q: (d(q), q))
            self.order[pak] = [names[q] for q in chain if names[q] in index] + [pak]
            parents = set(directory.get(pid, ("", []))[1]) if pid is not None else set()
            sib = [q for q, (n, ps) in directory.items()
                   if q < (pid or 0) and set(ps) & parents and is_level(n) and n in index]
            self.previous[pak] = [names[q] for q in sorted(sib, reverse=True)]
        self.memo = {}

    def keys(self, kind, h):
        return self.hash_keys.get((kind, h), set())

    def learn(self, rows):
        self.drawn.clear()
        self.memo = {}
        for row in rows:
            if not row.hits:
                continue
            vs, ps = int(row.r["vsHash"], 16), int(row.r["psHash"], 16)
            for k in self.keys("vs", vs):
                self.drawn[("vs", k)][vs] += 1
            for k in self.keys("ps", ps):
                self.drawn[("ps", k)][ps] += 1

    def variants(self, pak, kind, key, own):
        if not key:
            return (own,)
        k = (pak, kind, key, self.mode)
        if k not in self.memo:
            chain = self.provider(pak, kind, key, own)
            drawn = self.drawn.get((kind, key))
            if self.mode == "all":
                out = tuple(sorted(self.key_hashes[(kind, key)]))
            elif self.mode.startswith("chain+prev"):
                out = [chain]
                if not any((kind, key) in self.first[a] for a in self.order[pak][:-1]):
                    prev = next((self.first[a][(kind, key)] for a in self.previous[pak]
                                 if (kind, key) in self.first[a]), None)
                    if prev is not None and prev not in out:
                        out.append(prev)
                if self.mode == "chain+prev+drawn" and drawn:
                    best = max(sorted(drawn), key=lambda h: drawn[h])
                    if best not in out:
                        out.append(best)
                out = tuple(out)
            elif self.mode == "chain" or not drawn:
                out = (chain,)
            else:
                best = max(sorted(drawn), key=lambda h: drawn[h])
                out = (best,) if self.mode == "drawn" or best == chain else (best, chain)
            self.memo[k] = out
        return self.memo[k]

    def provider(self, pak, kind, key, own):
        if not key:
            return own
        return next((self.first[a][(kind, key)] for a in self.order[pak]
                     if (kind, key) in self.first[a]), own)


def label(rows, index, directory, keys):
    by_key = defaultdict(list)
    for pak, mats in index.items():
        for mi, m in enumerate(mats):
            for si, sl in enumerate(m.slots):
                by_key[(sl.vs_key, sl.ps_key, sl.decl)].append((pak, mi, si))
    names = {pid: v[0] for pid, v in directory.items()}
    for row in rows:
        r = row.r
        biased = r["depthBias"] not in ("0", "") or r["slopeScaledDepthBias"] not in ("0", "0.0", "")
        caster = biased and r["rtCount"] == "0"
        row.core = core_of(r)
        row.m = 0.0
        row.bias = (BIAS_SHADOW if caster else BIAS_LITERAL) if biased else BIAS_NONE
        if r.get("velocity", "0") != "0":
            continue
        vs, ps = int(r["vsHash"], 16), int(r["psHash"], 16)
        hits = []
        for kv in keys.keys("vs", vs):
            for kp in (keys.keys("ps", ps) if ps else {0}):
                hits.extend(by_key.get((kv, kp, r["declRaw"]), ()))
        if not hits:
            continue
        resident = set()
        for p in row.packages:
            for a in ancestors(directory, p):
                resident.add(names[a])
        near = [h for h in hits if h[0] in resident]
        row.owners = {h[0] for h in near}
        hits = near or hits
        if len(hits) > MAX_HITS:
            hits = hits[::len(hits) // MAX_HITS + 1]
        if row.bias == BIAS_LITERAL:
            ms = {index[p][mi].header["unk212"] for p, mi, _ in hits
                  if index[p][mi].header["materialFlags"] & FLAG_BIASED}
            if len(ms) == 1 and all(index[p][mi].header["materialFlags"] & FLAG_BIASED
                                    for p, mi, _ in hits):
                row.bias, row.m = BIAS_MATERIAL, ms.pop()
        row.hits = hits


def row_key(row):
    r = row.r
    return (int(r["vsHash"], 16), int(r["psHash"], 16), r["declRaw"],
            int(r["strides"].split("|")[0]), row.core, row.bias)


def evaluate(rows, index, directory, keys, folds=5, **kw):
    names = {pid: v[0] for pid, v in directory.items()}
    levels = sorted({p for row in rows if row.hits for p in row.packages
                     if p in names and is_level(names[p])})
    found = found_live = total = predicted = 0
    per = []

    def keyed(vs, ps, rest, vk=None, pk=None):
        vks = {vk} if vk else (keys.keys("vs", vs) or {("h", vs)})
        pks = {pk} if pk is not None else (keys.keys("ps", ps) if ps else {0}) or {("h", ps)}
        return {(a, b) + rest for a in vks for b in pks}
    for k in range(folds):
        held = set(levels[k::folds])
        train = [r for r in rows if not (r.packages & held)]
        model = Model(index, keys, **kw).fit(train)
        for p in held:
            pak = names[p]
            if pak not in index:
                continue
            drawn = [r for r in rows if p in r.packages and r.hits and r.bias != BIAS_LITERAL]
            own = [r for r in drawn if any(h[0] == pak for h in r.hits)]
            if not own:
                continue
            pred = model.derive(pak)
            pred_keys = {(a, b, c, d, e, f) for a, b, c, d, e, f, _ in pred}
            hit = sum(1 for r in own if row_key(r) in pred_keys)
            live = set()
            for a, b, c, d, e, f, g in pred:
                vk, pk = model.row_keys.get((pak, (a, b, c, d, e, f, g)), (0, 0))
                live |= keyed(a, b, (c, d, e, f), vk or None, pk)
            found_live += sum(1 for r in own if keyed(*row_key(r)[:2], row_key(r)[2:]) & live)
            found += hit
            total += len(own)
            predicted += len(pred)
            per.append((pak, hit, len(own), len(pred)))
    return found, total, predicted, per, found_live


def captured_keys_of(row, index, kid):
    vk = {index[p][mi].slots[si].vs_key for p, mi, si in row.hits}
    pk = {index[p][mi].slots[si].ps_key for p, mi, si in row.hits}
    return (kid("v", vk.pop()) if len(vk) == 1 else "",
            kid("p", pk.pop()) if len(pk) == 1 else "")


def velocity_forms(cores, core_id):
    out = []
    for vi, core in enumerate(cores):
        r = dict(zip(CORE_COLUMNS, core))
        n = int(r["rtCount"] or 0)
        if r["velocity"] != "1" or n < 1:
            continue
        p = dict(r, velocity="0", rtCount=str(n - 1))
        fmts = p["rtFormats"].split("|")
        fmts[n - 1] = "0"
        p["rtFormats"] = "|".join(fmts)
        p[f"blend{n - 1}"] = "0|0|0|0|0|0|0|0"
        pc = tuple(p[c] for c in CORE_COLUMNS)
        if pc in core_id:
            out.append((core_id[pc], vi))
    return sorted(out)


def check_set(path):
    decls = cores = 0
    bad = []

    def num(x, base=10, signed=False):
        if signed and x.startswith("-"):
            x = x[1:]
        try:
            return x != "" and int(x, base) >= 0 and "x" not in x.lower() and "+" not in x
        except ValueError:
            return False

    def flt(x):
        try:
            float(x)
            return x != ""
        except ValueError:
            return False

    for n, line in enumerate(Path(path).read_text(encoding="utf-8").splitlines(), 1):
        f = line.split("\t")
        why = None
        if f[0] == "decl":
            decls += 1
        elif f[0] == "core":
            cores += 1
        elif f[0] == "vkey":
            if len(f) != 4 or f[1] not in ("v", "p") or not num(f[2], 16) or \
                    not all(num(h, 16) for h in f[3].split("|")):
                why = "vkey"
        elif f[0] == "vcore":
            if len(f) != 3 or not (num(f[1]) and num(f[2])) or max(int(f[1]), int(f[2])) >= cores:
                why = "vcore"
        elif f[0] == "row":
            if len(f) != 16 or not all(x == "" or num(x) for x in f[14:16]):
                why = f"{len(f)} fields"
            elif not (num(f[2], 16) and num(f[3], 16) and num(f[12], 16) and num(f[13])):
                why = "number"
            elif not num(f[4]) or int(f[4]) >= decls or not num(f[6]) or int(f[6]) >= cores:
                why = "reference"
            elif not num(f[7]) or int(f[7]) > 3 or not all(num(x) for x in f[5].split("|")):
                why = "bias/strides"
            elif f[7] == "1" and not flt(f[8]):
                why = "material offset"
            elif f[7] == "3" and not (len(f[8].split("/")) == 2 and num(f[8].split("/")[0], signed=True)
                                      and flt(f[8].split("/")[1])):
                why = "literal offset"
        if why:
            bad.append((n, why, line[:120]))
    if bad:
        for b in bad[:10]:
            print(f"[derive] line {b[0]} would not parse ({b[1]}): {b[2]}", file=sys.stderr)
        sys.exit(f"[derive] {len(bad)} line(s) of {path} would not parse; not usable")
    print(f"[derive] checked {path}: every line parses")


def write_set(path, inc, cores, decls, vcores, vkeys, packages, shadows, out_rows, summary, evidence):
    lines = FORMAT.splitlines()
    lines += [f"# {s}" for s in summary]
    lines.append("header\t" + ",".join(COLUMNS))
    for i, core in enumerate(cores):
        r = dict(zip(CORE_COLUMNS, core))
        full = [r.get(c, "") for c in COLUMNS]
        for c, v in (("vsHash", "0" * 16), ("psHash", "0" * 16), ("spec", "0"),
                     ("layoutKey", "0" * 16), ("declRaw", ""),
                     ("strides", "0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0"), ("depthBias", "0"),
                     ("slopeScaledDepthBias", "0"), ("targetScale", "1"), ("frame", "0"),
                     ("session", "core"), ("package", ""), ("msaa", "0")):
            full[COLUMNS.index(c)] = v
        lines.append(f"core\t{i}\t" + ",".join(full))
    for plain, vel in vcores:
        lines.append(f"vcore\t{plain}\t{vel}")
    for kind, key, hashes in vkeys:
        lines.append(f"vkey\t{kind}\t{key:x}\t" + "|".join(f"{h:016x}" for h in hashes))
    for i, d in enumerate(decls):
        lines.append(f"decl\t{i}\t{d}")
    for pid, (name, parents, level) in sorted(packages.items()):
        lines.append(f"pkg\t{pid:x}\t{name}\t{'|'.join(f'{p:x}' for p in parents)}\t{int(level)}")
    for pid, vals in sorted(shadows.items()):
        for b, s in sorted(vals):
            lines.append(f"shadow\t{pid:x}\t{b}\t{s}")
    for r in out_rows:
        lines.append("row\t" + "\t".join(r))
    lines += ["cap\t" + e for e in evidence]
    text = "\n".join(lines) + "\n"
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(text, encoding="utf-8", newline="\n")
    inc_lines = ["// Generated by tools/pso/pso_derive.py from config/pso/eot_pso.tsv; do not edit."]
    for line in text.splitlines():
        if line.startswith("#") or line.startswith("cap\t"):
            continue
        inc_lines.append('"' + line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t") + '",')
    Path(inc).write_text("\n".join(inc_lines) + "\n", encoding="utf-8", newline="\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("captures", nargs="*", help="extra capture files or folders")
    ap.add_argument("--paks", default=str(DEFAULT_PAKS))
    ap.add_argument("-o", "--out", default=str(DEFAULT_OUT))
    ap.add_argument("--inc", default=str(DEFAULT_INC))
    ap.add_argument("--eval-only", action="store_true")
    ap.add_argument("--folds", type=int, default=5)
    ap.add_argument("--inc-threshold", type=float, default=0.05)
    ap.add_argument("--core-share", type=float, default=0.04)
    ap.add_argument("--min-global-levels", type=int, default=4,
                    help="a captured non-material row drawn in this many levels goes to the boot set")
    args = ap.parse_args()

    index, initializers = load_paks(args.paks)
    directory = load_directory()
    names = {pid: v[0] for pid, v in directory.items()}
    pak_ids = {v[0]: pid for pid, v in directory.items()}
    masks = load_shader_masks(DEFAULT_SHADER_CACHE)
    rooms = {pid for pid, (name, _) in directory.items() if is_level(name) and name not in BOOT_PACKAGES}
    rows, nfiles = load_captures([*DEFAULT_CAPTURES, *args.captures], masks, args.out, rooms)
    keys = ShaderKeys(index, directory)
    label(rows, index, directory, keys)
    material = [r for r in rows if r.hits]
    print(f"[derive] {nfiles} capture files -> {len(rows)} distinct pipelines; "
          f"{len(material)} labelled to a material record, {len(rows) - len(material)} other")
    kw = {"inc_threshold": args.inc_threshold, "core_share": args.core_share}
    found, total, predicted, per, found_live = evaluate(rows, index, directory, keys, args.folds, **kw)
    print(f"[derive] held-out levels: {found}/{total} drawn material pipelines predicted "
          f"({100.0 * found / max(total, 1):.1f}%), {found_live} ({100.0 * found_live / max(total, 1):.1f}%) "
          f"with the live shader variants, {predicted} derived for those paks")
    for pak, hit, n, p in sorted(per, key=lambda x: x[1] / max(x[2], 1))[:12]:
        print(f"           {pak[:36]:<36} {hit:>4}/{n:<4} of {p} derived")
    if args.eval_only:
        return

    model = Model(index, keys, **kw).fit(rows)
    summary = []
    cores, core_id = [], {}
    decls, decl_id = [], {}

    def cid(core):
        if core not in core_id:
            core_id[core] = len(cores)
            cores.append(core)
        return core_id[core]

    def did(decl):
        if decl not in decl_id:
            decl_id[decl] = len(decls)
            decls.append(decl)
        return decl_id[decl]

    vkeys = sorted((("v" if kind == "vs" else "p"), key, sorted(h))
                   for (kind, key), h in keys.key_hashes.items() if key and len(h) > 1)
    vkey_id = {(kind, key): i for i, (kind, key, _) in enumerate(vkeys)}

    def kid(kind, key):
        i = vkey_id.get((kind, key))
        return "" if i is None else str(i)

    out_rows = []
    seen = set()
    core_msaa, core_files, core_prev = defaultdict(int), defaultdict(set), defaultdict(int)
    for row in rows:
        core_msaa[row.core] |= row.msaa
        core_files[row.core] |= row.msaa_files
        core_prev[row.core] = max(core_prev[row.core], row.msaa_prev)
    core_sessions = {c: max(len(core_files[c]), core_prev[c]) for c in core_msaa}
    msaa_use = {c: (core_msaa[c] if core_sessions[c] >= MSAA_MIN_SESSIONS else 0) for c in core_msaa}
    shadows = defaultdict(set)
    captured_keys = set()
    boot_ids = {pak_ids[n] for n in BOOT_PACKAGES if n in pak_ids}
    for row in rows:
        r = row.r
        level_tags = [p for p in row.packages if p in names and is_level(names[p])]
        if row.bias == BIAS_SHADOW:
            for p in level_tags:
                shadows[p].add((int(r["depthBias"]), r["slopeScaledDepthBias"]))
        owners = {pak_ids[p] for p in row.owners if p in pak_ids} | set(row.packages)
        if (not row.hits and len(level_tags) >= args.min_global_levels) or not row.packages:
            owners = {0}
        if row.packages & boot_ids:
            owners.add(0)
        m = ""
        if row.bias == BIAS_MATERIAL:
            m = f"{row.m:.6g}"
        elif row.bias == BIAS_LITERAL:
            m = f"{r['depthBias']}/{r['slopeScaledDepthBias']}"
        stride = short_strides(r["strides"])
        tags = "|".join(f"{p:x}" for p in sorted(row.packages))
        key = (r["vsHash"], r["psHash"], r["declRaw"], stride, row.core, row.bias, m, r.get("spec") or "0")
        if key in seen:
            continue
        seen.add(key)
        for pid in owners:
            captured_keys.add((pid,) + key[:-1])
        out_rows.append(["|".join(f"{p:x}" for p in sorted(owners)), r["vsHash"], r["psHash"],
                         str(did(r["declRaw"])), stride, str(cid(row.core)), str(row.bias), m, "c",
                         str(row.frame), tags, r.get("spec") or "0", str(msaa_use[row.core]),
                         *captured_keys_of(row, index, kid)])
    captured = len(out_rows)
    from_paks = 0
    for pid, (name, _) in directory.items():
        if not is_level(name) or name not in index:
            continue
        before = len(shadows[pid])
        for a in ancestors(directory, pid):
            for _, units, slope in initializers.get(names[a], []):
                shadows[pid].add((units, slope))
        shadows[pid] |= GLOBAL_SHADOW
        from_paks += len(shadows[pid]) - before
    derived_per = {}
    for pak in sorted(index):
        pid = pak_ids.get(pak)
        if pid is None:
            continue
        n = 0
        derived = model.derive(pak)
        for vs, ps, decl, stride0, core, bias, mm in sorted(derived, key=lambda k: (-derived[k], repr(k))):
            stride = short_strides(strides_text(stride0, decl))
            m = f"{mm:.6g}" if bias == BIAS_MATERIAL else ""
            key = (pid, f"{vs:016x}", f"{ps:016x}", decl, stride, core, bias, m)
            if key in captured_keys or key in seen:
                continue
            seen.add(key)
            vk, pk = model.row_keys.get((pak, (vs, ps, decl, stride0, core, bias, mm)), (0, 0))
            sp = model.row_spec.get((pak, (vs, ps, decl, stride0, core, bias, mm)), SPEC_EITHER)
            out_rows.append([f"{pid:x}", f"{vs:016x}", f"{ps:016x}", str(did(decl)), stride,
                             str(cid(core)), str(bias), m, "d", "0", "", f"{sp:x}",
                             str(msaa_use.get(core, 0)), kid("v", vk), kid("p", pk)])
            n += 1
        derived_per[pak] = n
    missing = sorted(v[0] for pid, v in directory.items()
                     if v[0] not in index and not v[0].startswith("_"))
    packages = {pid: (name, parents, is_level(name)) for pid, (name, parents) in directory.items()}
    vcores = velocity_forms(cores, core_id)
    summary.append(f"{len(rows)} captured pipelines ({nfiles} files): {captured} captured rows; "
                   f"{len(out_rows) - captured} derived from {len(index)} paks; {len(cores)} cores, "
                   f"{len(decls)} declarations")
    summary.append(f"shadow offsets: {sum(len(v) for v in shadows.values())} over {len(shadows)} rooms "
                   f"({from_paks} from the paks' ShadowMapInitializers and the global one)")
    summary.append(f"held-out levels: {found}/{total} drawn material pipelines predicted "
                   f"({100.0 * found / max(total, 1):.1f}%; {100.0 * found_live / max(total, 1):.1f}% with "
                   f"the live shader variants), {predicted} derived for those paks")
    if missing:
        summary.append("paks not read (not in the pak folder): " + " ".join(missing))
    evidence = []
    for row in rows:
        r = dict(row.r, frame=str(row.frame), session=f"msaa{core_sessions[row.core]}",
                 msaa=str(row.msaa), package="|".join(f"{p:x}" for p in sorted(row.packages)))
        evidence.append(row_line(r))
    summary.append(f"{len(vcores)} states with a motion-vector form; rows by msaa use: "
                   + ", ".join(f"{k} {v}" for k, v in sorted(Counter(r[12] for r in out_rows).items())))
    summary.append(f"{len(vkeys)} shader keys with several containers (vkey)")
    write_set(args.out, args.inc, cores, decls, vcores, vkeys, packages, shadows, out_rows, summary,
              evidence)
    check_set(args.out)
    for line in summary:
        print("[derive] " + line)
    big = sorted(derived_per.items(), key=lambda x: -x[1])[:10]
    print("[derive] most derived rows: " + ", ".join(f"{k} {v}" for k, v in big))
    print(f"[derive] wrote {args.out} and {args.inc}")


if __name__ == "__main__":
    main()
