#!/usr/bin/env python3
import argparse
import csv
import io
import re
import sys
from collections import defaultdict
from pathlib import Path

SCHEMA_VERSION = 1
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "src" / "gpu" / "pipeline" / "cache" / "eot_pso_templates.inc"
SPEC_LAYOUT_BITS = 0x5
PAIRS_HEADER = "vsHash,psHash,technique,pass"
CLEAR = {"vsHash": "0" * 16, "psHash": "0" * 16, "layoutKey": "0" * 16, "declRaw": "",
         "frame": "0", "session": "template"}


def canon_decl(hexstr):
    out = []
    for i in range(0, len(hexstr), 24):
        e = hexstr[i:i + 24]
        out.append(e[:22] + "00" if len(e) == 24 else e)
    return "".join(out)


def read_csv(path):
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    body = [l for l in text.splitlines() if l.strip() and not l.startswith("#")]
    if not body:
        return None, []
    reader = csv.DictReader(io.StringIO("\n".join(body)))
    return reader.fieldnames, list(reader)


def collect(inputs):
    files = []
    for raw in inputs:
        p = Path(raw)
        if p.is_dir():
            files.extend(sorted(p.rglob("*.csv")))
        elif p.is_file():
            files.append(p)
        else:
            sys.stderr.write(f"warning: missing {p}\n")
    return files


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="capture CSVs / merged table / pso_pairs files, or folders")
    ap.add_argument("-o", "--output", default=str(DEFAULT_OUT))
    args = ap.parse_args()

    pair_slots = defaultdict(set)
    vs_slots = defaultdict(set)
    captures = []
    columns = None
    for f in collect(args.inputs):
        if f.name.startswith("pso_predicted_"):
            continue
        cols, rows = read_csv(f)
        if not rows:
            continue
        if cols[:4] == PAIRS_HEADER.split(","):
            for r in rows:
                slot = (int(r["technique"]), int(r["pass"]), int(r.get("class", "0") or "0", 16))
                pair_slots[(r["vsHash"].lower(), r["psHash"].lower())].add(slot)
                vs_slots[r["vsHash"].lower()].add(slot)
        elif cols and cols[0] == "vsHash":
            if columns is None:
                columns = cols
            elif cols != columns:
                sys.stderr.write(f"warning: {f}: column set differs; skipped\n")
                continue
            captures.extend(rows)
        else:
            sys.stderr.write(f"warning: {f}: unrecognised header; skipped\n")

    if not pair_slots:
        sys.exit("error: no pso_pairs_*.csv rows found (run the game with the predictor on first)")
    if not captures:
        sys.exit("error: no capture rows found")

    templates = {}
    matched = unmatched = 0
    for r in captures:
        vs, ps = r["vsHash"].lower(), r["psHash"].lower()
        slots = pair_slots.get((vs, ps))
        if not slots and int(ps, 16) == 0:
            slots = vs_slots.get(vs)
        if not slots:
            unmatched += 1
            continue
        matched += 1
        t = dict(r)
        t.update(CLEAR)
        strides = t["strides"].split("|")
        strides[0] = "0"
        t["strides"] = "|".join(strides)
        t["spec"] = format(int(t["spec"], 16) & ~SPEC_LAYOUT_BITS, "x")
        identity = tuple(t[c] for c in columns if c not in ("frame", "session"))
        for tech, pas, cls in slots:
            templates.setdefault((tech, pas, cls, identity), t)

    rows = sorted(templates.items())
    out = io.StringIO()
    out.write(f"// eot-pso-templates v{SCHEMA_VERSION}: {len(rows)} template(s). "
              "Generated by tools/pso/pso_gen_templates.py; do not edit.\n")
    out.write(f'"technique,pass,class,{",".join(columns)}",\n')
    per_tech = defaultdict(int)
    for (tech, pas, cls, _), t in rows:
        line = io.StringIO()
        csv.writer(line, lineterminator="").writerow([tech, pas, format(cls, "x")] + [t.get(c, "") for c in columns])
        out.write(f'"{line.getvalue()}",\n')
        per_tech[tech] += 1
    Path(args.output).write_text(out.getvalue(), encoding="utf-8", newline="\n")
    print(f"{args.output}: {len(rows)} templates from {matched} matched capture rows "
          f"({unmatched} rows with a shader pair no model slot has reported); "
          f"{len(pair_slots)} pairs known")
    print("templates per technique: " + ", ".join(f"{k}:{v}" for k, v in sorted(per_tech.items())))


if __name__ == "__main__":
    main()
