#!/usr/bin/env python3
import argparse
import csv
import sys
from collections import Counter, defaultdict
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pso_common import (COLUMNS, DEFAULT_SHADER_CACHE, REPO_ROOT, canonicalize,  # noqa: E402
                        collect_inputs, identity, is_capture, load_shader_masks, read_rows,
                        row_line)
from pso_paks import (DEFAULT_PAKS, TECHNIQUES, ancestors, load_directory,  # noqa: E402
                      load_index)

FORMAT = """\
# eot-pso-set v1: the pipelines the renderer builds ahead of the draws that
# use them. Generated by tools/pso/pso_derive.py from the paks and the
# captures; do not edit. Tab-separated records:
#   core   <id> <v4 pipeline row: the state; shaders, declaration, strides
#          and polygon offset empty>
#   decl   <id> <declaration elements, hex>
#   pkg    <id> <name> <parent ids> <level 0/1>
#   shadow <pkg> <depthBias> <slope>        a level's shadow-camera offset
#   cap    <v4 pipeline row>   the merged captures the set was made from
#          (the generator reads them back; not compiled in)
#   row    <pkg> <vs> <ps> <decl> <strides> <core> <bias> <m> <source>
#          <frame> <tags> <spec>
#          pkg: the packages whose load queues the row (|-joined), 0 = the boot;
#          bias 0 none, 1 the material's (m: offset m*1e-5, slope m*2),
#          2 the level's shadow cameras, 3 literal (m = "depthBias/slope");
#          source c captured (frame: first drawn; tags: the packages it was
#          drawn under; spec: the specialization bits it was drawn with),
#          d derived from the pak (likeliest first)
"""

DEFAULT_OUT = REPO_ROOT / "config" / "pso" / "eot_pso.tsv"
DEFAULT_INC = REPO_ROOT / "src" / "gpu" / "pipeline" / "cache" / "eot_pso.inc"
DEFAULT_CAPTURES = [REPO_ROOT / "pso", REPO_ROOT / "out" / "build" / "win-amd64-relwithdebinfo" / "pso"]

DRAW_COLUMNS = {"vsHash", "psHash", "spec", "layoutKey", "declRaw", "strides", "frame", "session",
                "package", "depthBias", "slopeScaledDepthBias", "targetScale"}
CORE_COLUMNS = [c for c in COLUMNS if c not in DRAW_COLUMNS]

BIAS_NONE, BIAS_MATERIAL, BIAS_SHADOW, BIAS_LITERAL = 0, 1, 2, 3
MAX_HITS = 48
FLAG_BIASED = 0x100

DECL_TYPE_SIZE = {36: 4, 37: 8, 57: 12, 38: 16, 6: 4, 10: 2, 2: 1, 25: 4, 26: 8, 24: 2, 31: 4, 32: 8,
                  30: 2, 33: 4, 34: 8, 7: 4, 16: 4, 17: 4}
SETS_FOR_MESH = {0: (0,), 1: (1,), 2: (0, 2), 3: (1, 3), 4: (0,)}


BOOT_PACKAGES = ("Main", "Common", "Legal", "FrontScreen", "01A_SMA_PortalRoom_Pip")


def is_level(name):
    return name[:1].isdigit()


def packed_strides(decl):
    ends = defaultdict(int)
    for i in range(0, len(decl), 24):
        e = bytes.fromhex(decl[i:i + 24])
        stream, off = int.from_bytes(e[0:2], "big"), int.from_bytes(e[2:4], "big")
        if stream == 0xFF:
            break
        size = DECL_TYPE_SIZE.get(int.from_bytes(e[4:8], "big") & 0x3F, 0)
        ends[stream] = max(ends[stream], off + size)
    return {s: (v + 3) & ~3 for s, v in ends.items()}


def strides_text(stream0, decl):
    st = [0] * 16
    for s, v in packed_strides(decl).items():
        if s < 16:
            st[s] = v
    st[0] = stream0
    return "|".join(str(x) for x in st)


def short_strides(full):
    parts = full.split("|")
    while len(parts) > 1 and parts[-1] == "0":
        parts.pop()
    return "|".join(parts)


class Row:
    __slots__ = ("r", "packages", "frame", "hits", "owners", "core", "bias", "m")

    def __init__(self, r):
        self.r = r
        self.packages = {int(p, 16) for p in (r.get("package") or "").split("|") if p}
        self.frame = int(r.get("frame") or 0)
        self.hits = []
        self.owners = set()


def core_of(r):
    return tuple(r[c] for c in CORE_COLUMNS)


def read_set_captures(path):
    p = Path(path)
    if not p.exists():
        return []
    header, out = None, []
    for line in p.read_text(encoding="utf-8").splitlines():
        if line.startswith("header\t"):
            header = line.split("\t", 1)[1].split(",")
        elif line.startswith("cap\t") and header:
            out.append(dict(zip(header, next(csv.reader([line.split("\t", 1)[1]])))))
    return out


def load_captures(inputs, masks, previous=None):
    files = [p for p in collect_inputs(inputs) if is_capture(p) or p.name.startswith("eot_pipelines")]
    rows = {}
    sources = [read_rows(f)[1] for f in files]
    if previous:
        sources.append(read_set_captures(previous))
    for rs in sources:
        for r in rs:
            canonicalize(r, masks)
            k = identity(r)
            row = rows.get(k)
            if row is None:
                rows[k] = Row(r)
            else:
                row.packages |= {int(p, 16) for p in (r.get("package") or "").split("|") if p}
                f2 = int(r.get("frame") or 0)
                if f2 and (not row.frame or f2 < row.frame):
                    row.frame = f2
    return sorted(rows.values(), key=lambda x: (x.frame or 1 << 62, identity(x.r))), len(files)


def material_features(m):
    h = m.header
    f = {"env": m.kind == "env"}
    for b in range(32):
        f[f"mf{b}"] = bool(h["materialFlags"] >> b & 1)
    for i, bm in enumerate(m.stage_blend[:4]):
        f[f"st{i}blend{bm}"] = True
    for bm in (1, 2, 3):
        f[f"anyblend{bm}"] = bm in m.stage_blend
    groups = {u[2] for u in m.uses}
    for g in (4, 8, 18, -1, -2):
        f[f"rg{g}"] = g in groups
    flags = 0
    for u in m.uses:
        flags |= u[3]
    for b in range(5):
        f[f"df{b}"] = bool(flags >> b & 1)
    f["nouse"] = not m.uses
    for k in ("byte72", "byte73", "byte74", "byte75", "byte132", "byte133", "unk80", "unk116",
              "unk240", "unk134"):
        f[f"{k}={h[k]}"] = True
    for k in ("unk44", "unk48", "unk56", "unk60", "unk64", "unk68", "unk76", "unk84", "unk88",
              "unk92", "unk96", "unk124", "unk212", "unk216", "unk236"):
        f[f"{k}!=0"] = h[k] != 0
    return f


def slot_features(s):
    f = {f"t{s.technique}": True, f"set{s.set}": True, "nops": s.ps == 0}
    for b in range(32):
        f[f"gf{b}"] = bool(s.generic_flags >> b & 1)
        f[f"lf{b}"] = bool(s.lighting_flags >> b & 1)
    sf = 0
    for x in s.stage_flags:
        sf |= x
    for b in range(20):
        f[f"sf{b}"] = bool(sf >> b & 1)
    return f


class Tree:
    def __init__(self, min_leaf=8, max_depth=14, min_gain=1e-3):
        self.min_leaf, self.max_depth, self.min_gain = min_leaf, max_depth, min_gain

    def fit(self, samples):
        merged = defaultdict(float)
        for f, y, w in samples:
            merged[(f, y)] += w
        names = sorted({n for f, _ in merged for n in f})
        col = {n: i for i, n in enumerate(names)}
        labels = sorted({y for _, y in merged}, key=repr)
        lab = {y: i for i, y in enumerate(labels)}
        keys = list(merged)
        X = np.zeros((len(keys), len(names)), dtype=bool)
        y = np.zeros(len(keys), dtype=np.int64)
        w = np.zeros(len(keys))
        for i, (f, yy) in enumerate(keys):
            X[i, [col[n] for n in f]] = True
            y[i] = lab[yy]
            w[i] = merged[(f, yy)]
        self.names, self.labels = names, labels
        Y = np.zeros((len(keys), len(labels)))
        Y[np.arange(len(keys)), y] = w
        self.root = self._grow(X, Y, np.arange(len(keys)), 0)
        return self

    @staticmethod
    def _entropy_rows(C):
        n = C.sum(axis=-1, keepdims=True)
        p = np.divide(C, n, out=np.zeros_like(C), where=n > 0)
        with np.errstate(divide="ignore", invalid="ignore"):
            h = -np.where(p > 0, p * np.log2(p), 0.0).sum(axis=-1)
        return h, n[..., 0]

    def _grow(self, X, Y, idx, depth):
        counts_v = Y[idx].sum(axis=0)
        counts = {self.labels[i]: float(v) for i, v in enumerate(counts_v) if v > 0}
        node = {"counts": counts, "n": int(len(idx))}
        if depth >= self.max_depth or len(idx) < 2 * self.min_leaf or len(counts) <= 1:
            return node
        Xi, Yi = X[idx], Y[idx]
        yes_n = Xi.sum(axis=0)
        cy = Xi.T.astype(float) @ Yi
        cn = counts_v[None, :] - cy
        hy, wy = self._entropy_rows(cy)
        hn, wn = self._entropy_rows(cn)
        total = counts_v.sum()
        base, _ = self._entropy_rows(counts_v[None, :])
        gain = base[0] - (wy / total) * hy - (wn / total) * hn
        ok = (yes_n >= self.min_leaf) & (len(idx) - yes_n >= self.min_leaf)
        gain = np.where(ok, gain, -1.0)
        best = int(np.argmax(gain))
        if gain[best] < self.min_gain:
            return node
        node["split"] = self.names[best]
        mask = Xi[:, best]
        node["yes"] = self._grow(X, Y, idx[mask], depth + 1)
        node["no"] = self._grow(X, Y, idx[~mask], depth + 1)
        return node

    def leaf(self, features):
        node = self.root
        while "split" in node:
            node = node["yes"] if node["split"] in features else node["no"]
        return node


def feature_set(d):
    return frozenset(k for k, v in d.items() if v)


class Model:
    def __init__(self, index, inc_threshold=0.05, core_share=0.04):
        self.index = index
        self.inc_threshold = inc_threshold
        self.core_share = core_share
        self._mf = {}

    def mfeat(self, pak, mi):
        k = (pak, mi)
        if k not in self._mf:
            self._mf[k] = feature_set(material_features(self.index[pak][mi]))
        return self._mf[k]

    def features(self, pak, mi, si):
        m = self.index[pak][mi]
        return self.mfeat(pak, mi) | feature_set(slot_features(m.slots[si]))

    def fit(self, rows):
        core_samples = []
        drawn = defaultdict(set)
        for row in rows:
            if not row.hits:
                continue
            w = 1.0 / len(row.hits)
            for pak, mi, si in row.hits:
                core_samples.append((self.features(pak, mi, si), (row.core, row.bias), w))
                drawn[(pak, mi)].add(si)
        self.cores = Tree(min_leaf=6).fit(core_samples)
        inc_samples = []
        for (pak, mi), sis in drawn.items():
            m = self.index[pak][mi]
            sets = {m.slots[si].set for si in sis}
            for si, s in enumerate(m.slots):
                if s.set in sets:
                    inc_samples.append((self.features(pak, mi, si), si in sis, 1.0))
        self.inclusion = Tree(min_leaf=10).fit(inc_samples)
        self.inc_n = len(inc_samples)
        return self

    def inclusion_p(self, f):
        c = self.inclusion.leaf(f)["counts"]
        n = sum(c.values())
        return c.get(True, 0) / n if n > 0 else 0.0

    def included(self, f):
        return self.inclusion_p(f) >= self.inc_threshold

    def cores_for(self, f):
        c = self.cores.leaf(f)["counts"]
        n = sum(c.values())
        return [(k, v / n) for k, v in c.items() if v / n >= self.core_share]

    def derive(self, pak):
        out = {}
        for mi, m in enumerate(self.index[pak]):
            uses = defaultdict(set)
            for vset, stride, _, _ in m.uses:
                for s in SETS_FOR_MESH.get(vset, (0,)):
                    uses[s].add(stride)
            have = {s.set for s in m.slots}
            if not uses:
                for s in have - {4}:
                    uses[s].add(0)
            bias_m = m.header["unk212"] if m.header["materialFlags"] & FLAG_BIASED else 0.0
            for si, s in enumerate(m.slots):
                if s.set not in uses:
                    continue
                f = self.features(pak, mi, si)
                p_inc = self.inclusion_p(f)
                if p_inc < self.inc_threshold:
                    continue
                for (core, bias), share in self.cores_for(f):
                    if bias == BIAS_MATERIAL and not bias_m:
                        continue
                    mm = bias_m if bias == BIAS_MATERIAL else 0.0
                    for stride in uses[s.set]:
                        st = stride or packed_strides(s.decl).get(0, 0)
                        if st:
                            k = (s.vs, s.ps, s.decl, st, core, bias, round(mm, 6))
                            out[k] = max(out.get(k, 0.0), p_inc * share)
        return out


def label(rows, index, directory):
    by_key = defaultdict(list)
    for pak, mats in index.items():
        for mi, m in enumerate(mats):
            for si, s in enumerate(m.slots):
                by_key[(s.vs, s.ps, s.decl)].append((pak, mi, si))
    names = {pid: v[0] for pid, v in directory.items()}
    for row in rows:
        r = row.r
        biased = r["depthBias"] not in ("0", "") or r["slopeScaledDepthBias"] not in ("0", "0.0", "")
        caster = biased and r["rtCount"] == "0"
        row.core = core_of(r)
        row.m = 0.0
        row.bias = (BIAS_SHADOW if caster else BIAS_LITERAL) if biased else BIAS_NONE
        if r.get("velocity", "0") != "0":
            continue
        hits = by_key.get((int(r["vsHash"], 16), int(r["psHash"], 16), r["declRaw"]))
        if not hits:
            continue
        resident = set()
        for p in row.packages:
            for a in ancestors(directory, p):
                resident.add(names[a])
        near = [h for h in hits if h[0] in resident]
        row.owners = {h[0] for h in near}
        hits = near or hits
        if len(hits) > MAX_HITS:
            hits = hits[::len(hits) // MAX_HITS + 1]
        if row.bias == BIAS_LITERAL:
            ms = {index[p][mi].header["unk212"] for p, mi, _ in hits
                  if index[p][mi].header["materialFlags"] & FLAG_BIASED}
            if len(ms) == 1 and all(index[p][mi].header["materialFlags"] & FLAG_BIASED
                                    for p, mi, _ in hits):
                row.bias, row.m = BIAS_MATERIAL, ms.pop()
        row.hits = hits


def row_key(row):
    r = row.r
    return (int(r["vsHash"], 16), int(r["psHash"], 16), r["declRaw"],
            int(r["strides"].split("|")[0]), row.core, row.bias)


def evaluate(rows, index, directory, folds=5, **kw):
    names = {pid: v[0] for pid, v in directory.items()}
    levels = sorted({p for row in rows if row.hits for p in row.packages
                     if p in names and is_level(names[p])})
    found = total = predicted = 0
    per = []
    for k in range(folds):
        held = set(levels[k::folds])
        train = [r for r in rows if not (r.packages & held)]
        model = Model(index, **kw).fit(train)
        for p in held:
            pak = names[p]
            if pak not in index:
                continue
            drawn = [r for r in rows if p in r.packages and r.hits and r.bias != BIAS_LITERAL]
            own = [r for r in drawn if any(h[0] == pak for h in r.hits)]
            if not own:
                continue
            pred = model.derive(pak)
            keys = {(a, b, c, d, e, f) for a, b, c, d, e, f, _ in pred}
            hit = sum(1 for r in own if row_key(r) in keys)
            found += hit
            total += len(own)
            predicted += len(pred)
            per.append((pak, hit, len(own), len(pred)))
    return found, total, predicted, per


def write_set(path, inc, cores, decls, packages, shadows, out_rows, summary, evidence):
    lines = FORMAT.splitlines()
    lines += [f"# {s}" for s in summary]
    lines.append("header\t" + ",".join(COLUMNS))
    for i, core in enumerate(cores):
        r = dict(zip(CORE_COLUMNS, core))
        full = [r.get(c, "") for c in COLUMNS]
        for c, v in (("vsHash", "0" * 16), ("psHash", "0" * 16), ("spec", "0"),
                     ("layoutKey", "0" * 16), ("declRaw", ""),
                     ("strides", "0|0|0|0|0|0|0|0|0|0|0|0|0|0|0|0"), ("depthBias", "0"),
                     ("slopeScaledDepthBias", "0"), ("targetScale", "1"), ("frame", "0"),
                     ("session", "core"), ("package", "")):
            full[COLUMNS.index(c)] = v
        lines.append(f"core\t{i}\t" + ",".join(full))
    for i, d in enumerate(decls):
        lines.append(f"decl\t{i}\t{d}")
    for pid, (name, parents, level) in sorted(packages.items()):
        lines.append(f"pkg\t{pid:x}\t{name}\t{'|'.join(f'{p:x}' for p in parents)}\t{int(level)}")
    for pid, vals in sorted(shadows.items()):
        for b, s in sorted(vals):
            lines.append(f"shadow\t{pid:x}\t{b}\t{s}")
    for r in out_rows:
        lines.append("row\t" + "\t".join(r))
    lines += ["cap\t" + e for e in evidence]
    text = "\n".join(lines) + "\n"
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(text, encoding="utf-8", newline="\n")
    inc_lines = ["// Generated by tools/pso/pso_derive.py from config/pso/eot_pso.tsv; do not edit."]
    for line in text.splitlines():
        if line.startswith("#") or line.startswith("cap\t"):
            continue
        inc_lines.append('"' + line.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t") + '",')
    Path(inc).write_text("\n".join(inc_lines) + "\n", encoding="utf-8", newline="\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("captures", nargs="*", help="extra capture files or folders")
    ap.add_argument("--paks", default=str(DEFAULT_PAKS))
    ap.add_argument("-o", "--out", default=str(DEFAULT_OUT))
    ap.add_argument("--inc", default=str(DEFAULT_INC))
    ap.add_argument("--eval-only", action="store_true")
    ap.add_argument("--folds", type=int, default=5)
    ap.add_argument("--inc-threshold", type=float, default=0.05)
    ap.add_argument("--core-share", type=float, default=0.04)
    ap.add_argument("--min-global-levels", type=int, default=4,
                    help="a captured non-material row drawn in this many levels goes to the boot set")
    args = ap.parse_args()

    index = load_index(args.paks)
    directory = load_directory()
    names = {pid: v[0] for pid, v in directory.items()}
    pak_ids = {v[0]: pid for pid, v in directory.items()}
    masks = load_shader_masks(DEFAULT_SHADER_CACHE)
    rows, nfiles = load_captures([*DEFAULT_CAPTURES, *args.captures], masks, args.out)
    label(rows, index, directory)
    material = [r for r in rows if r.hits]
    print(f"[derive] {nfiles} capture files -> {len(rows)} distinct pipelines; "
          f"{len(material)} labelled to a material record, {len(rows) - len(material)} other")
    kw = {"inc_threshold": args.inc_threshold, "core_share": args.core_share}
    found, total, predicted, per = evaluate(rows, index, directory, args.folds, **kw)
    print(f"[derive] held-out levels: {found}/{total} drawn material pipelines predicted "
          f"({100.0 * found / max(total, 1):.1f}%), {predicted} derived for those paks")
    for pak, hit, n, p in sorted(per, key=lambda x: x[1] / max(x[2], 1))[:12]:
        print(f"           {pak[:36]:<36} {hit:>4}/{n:<4} of {p} derived")
    if args.eval_only:
        return

    model = Model(index, **kw).fit(rows)
    summary = []
    cores, core_id = [], {}
    decls, decl_id = [], {}

    def cid(core):
        if core not in core_id:
            core_id[core] = len(cores)
            cores.append(core)
        return core_id[core]

    def did(decl):
        if decl not in decl_id:
            decl_id[decl] = len(decls)
            decls.append(decl)
        return decl_id[decl]

    out_rows = []
    seen = set()
    shadows = defaultdict(set)
    captured_keys = set()
    boot_ids = {pak_ids[n] for n in BOOT_PACKAGES if n in pak_ids}
    for row in rows:
        r = row.r
        level_tags = [p for p in row.packages if p in names and is_level(names[p])]
        if row.bias == BIAS_SHADOW:
            for p in level_tags:
                shadows[p].add((int(r["depthBias"]), r["slopeScaledDepthBias"]))
        owners = {pak_ids[p] for p in row.owners if p in pak_ids} | set(row.packages)
        if (not row.hits and len(level_tags) >= args.min_global_levels) or not row.packages:
            owners = {0}
        if row.packages & boot_ids:
            owners.add(0)
        m = ""
        if row.bias == BIAS_MATERIAL:
            m = f"{row.m:.6g}"
        elif row.bias == BIAS_LITERAL:
            m = f"{r['depthBias']}/{r['slopeScaledDepthBias']}"
        stride = short_strides(r["strides"])
        tags = "|".join(f"{p:x}" for p in sorted(row.packages))
        key = (r["vsHash"], r["psHash"], r["declRaw"], stride, row.core, row.bias, m, r.get("spec") or "0")
        if key in seen:
            continue
        seen.add(key)
        for pid in owners:
            captured_keys.add((pid,) + key[:-1])
        out_rows.append(["|".join(f"{p:x}" for p in sorted(owners)), r["vsHash"], r["psHash"],
                         str(did(r["declRaw"])), stride, str(cid(row.core)), str(row.bias), m, "c",
                         str(row.frame), tags, r.get("spec") or "0"])
    captured = len(out_rows)
    derived_per = {}
    for pak in sorted(index):
        pid = pak_ids.get(pak)
        if pid is None:
            continue
        n = 0
        derived = model.derive(pak)
        for vs, ps, decl, stride0, core, bias, mm in sorted(derived, key=lambda k: (-derived[k], repr(k))):
            stride = short_strides(strides_text(stride0, decl))
            m = f"{mm:.6g}" if bias == BIAS_MATERIAL else ""
            key = (pid, f"{vs:016x}", f"{ps:016x}", decl, stride, core, bias, m)
            if key in captured_keys or key in seen:
                continue
            seen.add(key)
            out_rows.append([f"{pid:x}", f"{vs:016x}", f"{ps:016x}", str(did(decl)), stride,
                             str(cid(core)), str(bias), m, "d", "0", "", "0"])
            n += 1
        derived_per[pak] = n
    missing = sorted(v[0] for pid, v in directory.items()
                     if v[0] not in index and not v[0].startswith("_"))
    packages = {pid: (name, parents, is_level(name)) for pid, (name, parents) in directory.items()}
    summary.append(f"{len(rows)} captured pipelines ({nfiles} files): {captured} captured rows; "
                   f"{len(out_rows) - captured} derived from {len(index)} paks; {len(cores)} cores, "
                   f"{len(decls)} declarations")
    summary.append(f"held-out levels: {found}/{total} drawn material pipelines predicted "
                   f"({100.0 * found / max(total, 1):.1f}%), {predicted} derived for those paks")
    if missing:
        summary.append("paks not read (not in the pak folder): " + " ".join(missing))
    evidence = []
    for row in rows:
        r = dict(row.r, frame=str(row.frame), session="cap",
                 package="|".join(f"{p:x}" for p in sorted(row.packages)))
        evidence.append(row_line(r))
    write_set(args.out, args.inc, cores, decls, packages, shadows, out_rows, summary, evidence)
    for line in summary:
        print("[derive] " + line)
    big = sorted(derived_per.items(), key=lambda x: -x[1])[:10]
    print("[derive] most derived rows: " + ", ".join(f"{k} {v}" for k, v in big))
    print(f"[derive] wrote {args.out} and {args.inc}")


if __name__ == "__main__":
    main()
