#!/usr/bin/env python3
import argparse
import csv
import io
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

SCHEMA_VERSION = 1
VERSION_RE = re.compile(r"^#\s*eot-pso\s+v(\d+)\s*$")
DIAGNOSTIC_COLUMNS = {"layoutKey", "frame", "session"}
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SHADER_CACHE = REPO_ROOT / "generated" / "shader_cache.cpp"
DEFAULT_INC = REPO_ROOT / "src" / "gpu" / "pipeline" / "cache" / "eot_pipelines.inc"


def read_rows(path):
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    lines = text.splitlines()
    version = None
    body = []
    for line in lines:
        m = VERSION_RE.match(line)
        if m:
            version = int(m.group(1))
            continue
        if line.startswith("#") or not line.strip():
            continue
        body.append(line)
    if version is not None and version != SCHEMA_VERSION:
        sys.stderr.write(f"warning: {path}: schema v{version} != v{SCHEMA_VERSION}; skipped\n")
        return None, []
    if not body:
        return None, []
    reader = csv.DictReader(io.StringIO("\n".join(body)))
    rows = [r for r in reader if r.get("vsHash")]
    return reader.fieldnames, rows


def identity(row, columns):
    return tuple(row.get(c, "") for c in columns if c not in DIAGNOSTIC_COLUMNS)


def load_shader_hashes(path):
    try:
        text = Path(path).read_text(encoding="utf-8", errors="replace")
    except FileNotFoundError:
        return None
    hashes = set()
    for m in re.finditer(r"\{\s*0x([0-9A-Fa-f]+)\s*,", text):
        hashes.add(int(m.group(1), 16))
    return hashes or None


def collect_inputs(inputs):
    files = []
    for raw in inputs:
        p = Path(raw)
        if p.is_dir():
            found = sorted(p.rglob("*.csv"))
            if not found:
                sys.stderr.write(f"warning: no .csv files under {p}\n")
            files.extend(found)
        elif p.is_file():
            files.append(p)
        else:
            sys.stderr.write(f"warning: skipping missing path {p}\n")
    return files


def row_line(row, columns):
    out = io.StringIO()
    w = csv.writer(out, lineterminator="")
    w.writerow([row.get(c, "") for c in columns])
    return out.getvalue()


def emit_inc(rows, columns, path):
    lines = [
        f"// eot-pso v{SCHEMA_VERSION}: {len(rows)} pipeline(s). Generated by tools/pso/pso_merge.py; do not edit.",
        f'"{",".join(columns)}",',
    ]
    for r in rows:
        line = row_line(r, columns)
        line = line.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'"{line}",')
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def report(rows):
    by_pair = Counter((r["vsHash"], r["psHash"]) for r in rows)
    by_vs = Counter(r["vsHash"] for r in rows)
    sessions = Counter(r.get("session", "-") for r in rows)
    spec = Counter(r["spec"] for r in rows)
    print(f"{len(rows)} pipelines, {len(by_pair)} shader pairs, {len(by_vs)} vertex shaders, "
          f"{len(sessions)} session tags")
    print("top shader pairs (vs, ps): pipelines")
    for (vs, ps), n in by_pair.most_common(10):
        print(f"  {vs} {ps}: {n}")
    print("spec masks: " + ", ".join(f"{k}:{v}" for k, v in sorted(spec.items())))
    print("sessions: " + ", ".join(f"{k}:{v}" for k, v in sessions.most_common(20)))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="capture CSV file(s) or folder(s) scanned recursively")
    ap.add_argument("-o", "--output", help="merged CSV to write (accumulates unless --replace)")
    ap.add_argument("--inc", help=f"compiled-in table to regenerate (default: {DEFAULT_INC.relative_to(REPO_ROOT)} when -o is given)")
    ap.add_argument("--no-inc", action="store_true", help="do not write the .inc")
    ap.add_argument("--replace", action="store_true", help="discard rows already in -o instead of accumulating")
    ap.add_argument("--shader-cache", default=str(DEFAULT_SHADER_CACHE),
                    help="generated/shader_cache.cpp to validate shader hashes against ('' to skip)")
    ap.add_argument("--report", action="store_true", help="print coverage statistics of the merged set")
    args = ap.parse_args()

    files = collect_inputs(args.inputs)
    if not files:
        sys.exit("error: no input CSV files found")

    hashes = load_shader_hashes(args.shader_cache) if args.shader_cache else None
    if args.shader_cache and hashes is None:
        sys.stderr.write(f"warning: {args.shader_cache} not found; shader validation skipped\n")

    columns = None
    merged = {}
    per_file = []
    dropped_shader = 0
    for f in files:
        cols, rows = read_rows(f)
        if not rows:
            per_file.append((f, 0, 0))
            continue
        if columns is None:
            columns = cols
        elif cols != columns:
            sys.stderr.write(f"warning: {f}: column set differs from the first file; skipped\n")
            per_file.append((f, len(rows), 0))
            continue
        new = 0
        for r in rows:
            if hashes is not None:
                vs, ps = int(r["vsHash"], 16), int(r["psHash"], 16)
                if vs not in hashes or (ps and ps not in hashes):
                    dropped_shader += 1
                    continue
            key = identity(r, columns)
            if key not in merged:
                merged[key] = r
                new += 1
        per_file.append((f, len(rows), new))

    existing = 0
    if args.output and not args.replace and Path(args.output).is_file():
        cols, rows = read_rows(args.output)
        if rows and cols == columns or columns is None:
            columns = columns or cols
            for r in rows:
                key = identity(r, columns)
                if key not in merged:
                    merged[key] = r
                    existing += 1
        elif rows:
            sys.stderr.write(f"warning: {args.output}: column set differs; not accumulated\n")

    if columns is None:
        sys.exit("error: no rows found")

    rows = sorted(merged.values(), key=lambda r: identity(r, columns))
    for f, total, new in per_file:
        print(f"{f}: {total} rows, {new} new")
    print(f"merged: {len(rows)} pipelines ({existing} kept from {args.output or 'nothing'}, "
          f"{dropped_shader} dropped: shader not in cache)")

    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(f"# eot-pso v{SCHEMA_VERSION}\n")
            fh.write(",".join(columns) + "\n")
            for r in rows:
                fh.write(row_line(r, columns) + "\n")
        print(f"wrote {out}")
        if not args.no_inc:
            inc = Path(args.inc) if args.inc else DEFAULT_INC
            emit_inc(rows, columns, inc)
            print(f"wrote {inc} ({len(rows)} rows)")
    elif args.inc and not args.no_inc:
        emit_inc(rows, columns, Path(args.inc))
        print(f"wrote {args.inc} ({len(rows)} rows)")

    if args.report:
        report(rows)


if __name__ == "__main__":
    main()
