#!/usr/bin/env python3
import argparse
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from pso_common import (COLUMNS, DEFAULT_INC, DEFAULT_SHADER_CACHE, SCHEMA_VERSION,  # noqa: E402
                        canonicalize, collect_inputs, identity, is_capture, load_shader_masks,
                        merge_packages, read_rows, row_line, write_inc)


def report(rows):
    by_pair = Counter((r["vsHash"], r["psHash"]) for r in rows)
    by_vs = Counter(r["vsHash"] for r in rows)
    sessions = Counter(r.get("session", "-") for r in rows)
    packages = Counter()
    for r in rows:
        for p in (r.get("package") or "").split("|"):
            packages[p or "global"] += 1
    spec = Counter(r["spec"] for r in rows)
    print(f"{len(rows)} pipelines, {len(by_pair)} shader pairs, {len(by_vs)} vertex shaders, "
          f"{len(sessions)} session tags")
    print("top shader pairs (vs, ps): pipelines")
    for (vs, ps), n in by_pair.most_common(10):
        print(f"  {vs} {ps}: {n}")
    print("spec masks: " + ", ".join(f"{k}:{v}" for k, v in sorted(spec.items())))
    print("sessions: " + ", ".join(f"{k}:{v}" for k, v in sessions.most_common(20)))
    print("packages: " + ", ".join(f"{k}:{v}" for k, v in packages.most_common(20)))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("inputs", nargs="+", help="capture CSV file(s), the merged table, or folder(s) scanned recursively")
    ap.add_argument("-o", "--output", help="merged CSV to write (accumulates unless --replace)")
    ap.add_argument("--inc", help=f"compiled-in table to regenerate (default: {DEFAULT_INC.relative_to(Path.cwd()) if DEFAULT_INC.is_relative_to(Path.cwd()) else DEFAULT_INC} when -o is given)")
    ap.add_argument("--no-inc", action="store_true", help="do not write the .inc")
    ap.add_argument("--replace", action="store_true", help="discard rows already in -o instead of accumulating")
    ap.add_argument("--shader-cache", default=str(DEFAULT_SHADER_CACHE),
                    help="generated/shader_cache.cpp to validate shader hashes against ('' to skip)")
    ap.add_argument("--report", action="store_true", help="print coverage statistics of the merged set")
    args = ap.parse_args()

    files = collect_inputs(args.inputs)
    if not files:
        sys.exit("error: no input CSV files found")

    masks = load_shader_masks(args.shader_cache) if args.shader_cache else None
    if args.shader_cache and masks is None:
        sys.stderr.write(f"warning: {args.shader_cache} not found; shader validation skipped\n")

    merged = {}
    per_file = []
    dropped_shader = 0

    def absorb(rows):
        nonlocal dropped_shader
        new = 0
        for r in rows:
            canonicalize(r, masks)
            if masks is not None:
                vs, ps = int(r["vsHash"], 16), int(r["psHash"], 16)
                if vs not in masks or (ps and ps not in masks):
                    dropped_shader += 1
                    continue
            key = identity(r)
            if key in merged:
                merged[key]["package"] = merge_packages(merged[key].get("package"), r.get("package"))
            else:
                merged[key] = r
                new += 1
        return new

    for f in files:
        if f.name.startswith("pso_") and not is_capture(f):
            continue
        cols, rows = read_rows(f)
        if not rows:
            per_file.append((f, 0, 0))
            continue
        per_file.append((f, len(rows), absorb(rows)))

    existing = 0
    if args.output and not args.replace and Path(args.output).is_file():
        cols, rows = read_rows(args.output)
        if rows:
            existing = absorb(rows)

    if not merged:
        sys.exit("error: no rows found")

    rows = sorted(merged.values(), key=identity)
    for f, total, new in per_file:
        print(f"{f}: {total} rows, {new} new")
    print(f"merged: {len(rows)} pipelines ({existing} kept from {args.output or 'nothing'}, "
          f"{dropped_shader} dropped: shader not in cache)")

    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        with out.open("w", encoding="utf-8", newline="\n") as fh:
            fh.write(f"# eot-pso v{SCHEMA_VERSION}\n")
            fh.write(",".join(COLUMNS) + "\n")
            for r in rows:
                fh.write(row_line(r) + "\n")
        print(f"wrote {out}")
        if not args.no_inc:
            inc = Path(args.inc) if args.inc else DEFAULT_INC
            write_inc(inc, f"// eot-pso v{SCHEMA_VERSION}: {len(rows)} pipeline(s). Generated by tools/pso/pso_merge.py; do not edit.",
                      ",".join(COLUMNS), [row_line(r) for r in rows])
            print(f"wrote {inc} ({len(rows)} rows)")
    elif args.inc and not args.no_inc:
        write_inc(Path(args.inc), f"// eot-pso v{SCHEMA_VERSION}: {len(rows)} pipeline(s). Generated by tools/pso/pso_merge.py; do not edit.",
                  ",".join(COLUMNS), [row_line(r) for r in rows])
        print(f"wrote {args.inc} ({len(rows)} rows)")

    if args.report:
        report(rows)


if __name__ == "__main__":
    main()
