import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKZ = os.path.normpath(os.path.join(HERE, "..", "pkz"))
sys.path.insert(0, PKZ)
from make_strings import load  # noqa: E402  the TOML reader, tomllib or the subset

SOURCES = (
    (0x7ED, "ReeotMenu", "toml", "reeot_menu_strings.toml"),
    (0x7EE, "ReeotUI", "txt", "reeot_ui_strings.txt"),
    (0x7EC, "ReeotAchievements", "txt", os.path.join("generated", "reeot_ach_strings.txt")),
)


def name_crc(name):
    crc = 0xFFFFFFFF
    for byte in name.upper().encode("ascii"):
        crc ^= byte
        for _ in range(8):
            crc = (0xEDB88320 ^ (crc >> 1)) if crc & 1 else crc >> 1
    return crc ^ 0xFFFFFFFF


assert name_crc("TCRWindow_Choice") == 0x2CA86B19, "BUCRC must match the retail headers"


def read_list(path):
    out = {}
    with open(path, encoding="utf-8") as f:
        for raw in f:
            line = raw.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            name, tab, text = line.partition("\t")
            if not tab:
                sys.exit(f"{path}: expected NAME<TAB>text: {line}")
            out[name] = text
    return out


def escape(text):
    return text.replace("\\", "\\\\").replace("\n", "\\n").replace("\t", "\\t")


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    language, destination = sys.argv[1:]
    rows = []
    counts = []
    for package, table, kind, english_file in SOURCES:
        if kind == "toml":
            tables = load(os.path.join(PKZ, english_file))
            english = tables["en"]
            own = tables.get(language, {})
        else:
            english = read_list(os.path.join(PKZ, english_file))
            base, ext = os.path.splitext(os.path.basename(english_file))
            path = os.path.join(PKZ, f"{base}.{language}{ext}")
            own = read_list(path) if os.path.exists(path) else {}
        for name in own:
            if name not in english:
                sys.exit(f"{table}: {language} has {name}, which the English list does not")
        index = {name: i for i, name in enumerate(english)}
        for name, text in own.items():
            rows.append(f"{package}\t0\t{table}\t{index[name]}\t0\t{name_crc(name):08X}\t0\t-1\t{escape(text)}")
        counts.append(f"{table} {len(own)}/{len(english)}")

    os.makedirs(os.path.dirname(os.path.abspath(destination)), exist_ok=True)
    with open(destination, "w", encoding="utf-8", newline="\n") as out:
        out.write(f"# reeot text: the port's own strings in {language}, generated by "
                  "tools/lang/make_port_translation.py -- do not edit.\n")
        out.write("# package\ttable\ttableName\tstring\tsub\tcrc\tstart\tend\ttext\n")
        out.write("\n".join(rows) + "\n")
    print(f"{destination}: {len(rows)} rows ({', '.join(counts)})")


if __name__ == "__main__":
    main()
